# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo apt-get install clang libicu-dev
    mkdir swift-install
    cd swift-install
    wget https://swift.org/builds/swift-5.1.3-release/ubuntu1804/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
    tar -xvzf swift-5.1.3-RELEASE*
    export PATH=$(pwd)/swift-5.1.3-RELEASE-ubuntu18.04
    swift -version
  displayName: 'Install Swift'

- script: |
    swift test
  displayName: 'Run unit tests'
